#!/usr/bin/env python3

import argparse
import logging
import os
import sys

from dotenv import load_dotenv
import pendulum

from utils.my_llm import MY_LLM
from utils.notify import MY_CiscoWebex

# Get current date
now = pendulum.now().format('YYYY-MM-DD')

# Set up logging
log = logging.getLogger(__name__)
logging.basicConfig(
    format='%(asctime)s | %(message)s',
    datefmt='%Y-%m-%d %H:%M:%S',
    level=logging.INFO
)

# Set webexteamssdk logger to ERROR level
webex_log = logging.getLogger('webexteamssdk')
webex_log.setLevel(logging.ERROR)

# Load environment variables from .env file
load_dotenv()
webex_token = os.getenv("WEBEX_TOKEN")
webex = MY_CiscoWebex(access_token=webex_token)

def main(msg_id):
    webex.log_bot_name() # This can be removed
    webex.delete_msg(msg_id)

# Example usage
if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: delete_msg <message_id>")
        sys.exit(1)

    msg_id = sys.argv[1]
    log.info(f'{ "="*20 } Starting Script: { os.path.basename(__file__) } { "="*20 }')
    main(msg_id)
